sudo: required
services:
  - docker

before_install:
  - docker build -t ubermensch01/docker-k8s-react -f Dockerfile.dev .

script:
  - docker run ubermensch01/docker-k8s-react npm run test -- --coverage